services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: container-fisc-backend
    expose:
      - "5000"
    volumes:
      - ./data:/app/data
    env_file:
      - path: .env
        required: false
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: container-fisc-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
