version: '3.8'

services:
  fiscal-finance-api:
    build: .
    container_name: container-fisc
    ports:
      - "8080:5000"
    volumes:
      # Mapeia a pasta data/ local para o diretório de dados dentro do container,
      # garantindo que o banco de dados SQLite não seja perdido ao deletar o container.
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
